export enum CustomerOrderStatus {
  DRAFT = "DRAFT",
  AWAITING_CUSTOMER_CONFIRMATION = "AWAITING_CUSTOMER_CONFIRMATION",
  PENDING_VENDOR_CONFIRMATION = "PENDING_VENDOR_CONFIRMATION",
  PREPARING = "PREPARING",
  WAITING_CUSTOMER_DECISION = "WAITING_CUSTOMER_DECISION",
  READY = "READY",
  PICKED_UP = "PICKED_UP",
  IN_DELIVERY = "IN_DELIVERY",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  CANCELLED_BY_CUSTOMER = "CANCELLED_BY_CUSTOMER",
}
