export enum CustomerOrderStatus {
  PENDING_VENDOR_CONFIRMATION = "PENDING_VENDOR_CONFIRMATION",
  WAITING_CUSTOMER_DECISION = "WAITING_CUSTOMER_DECISION",
  READY = "READY",
  IN_DELIVERY = "IN_DELIVERY",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}
