export enum DeliveryStatus {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  ASSIGNED = "ASSIGNED",
  PICKED_UP = "PICKED_UP",
  ON_THE_WAY = "ON_THE_WAY",
  DELIVERED = "DELIVERED",
  FAILED = "FAILED",
}
