export enum VendorOrderStatus {
  PENDING = "PENDING",
  PROPOSAL_SENT = "PROPOSAL_SENT",
  CONFIRMED = "CONFIRMED",
  PICKED_UP = "PICKED_UP",
  ON_THE_WAY = "ON_THE_WAY",
  DELIVERED = "DELIVERED",
  CANCELLED = "CANCELLED",
}
